name: Run tests
on:
  push:
    paths: ["src/**", "!**/*.stories.*"]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and test
        run: |
          npm install
          npm run test